apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.infisical.kubeSecretRef }}
type: Opaque
stringData:
  AUTH_SECRET: {{ .Values.secrets.authSecret | quote }}
  ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | quote }}
  REDIS_URL: {{ .Values.redis.connectionUri | quote }}
  SITE_URL: {{ .Values.siteUrl | default (printf "https://%s" .Values.ingress.hostName) | quote }}
  DB_CONNECTION_URI: {{ .Values.postgresql.useExistingPostgresSecret.connectionUri | quote }}
