apiVersion: v1
kind: Secret
metadata:
    name: infisical-secrets
type: Opaque
stringData:
    AUTH_SECRET: {{ .Values.secrets.authSecret | default (randAlphaNum 32) | quote }}
    ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | default (randAlphaNum 16) | quote }}
    REDIS_URL: {{ .Values.redis.connectionUri | quote }}
    DB_CONNECTION_URI: {{ .Values.postgresql.useExistingPostgresSecret.connectionUri | quote }}
    SITE_URL: {{ .Values.siteUrl | default (printf "https://%s" .Values.ingress.host) | quote }}
