name: Release standalone docker image
on:
    push:
        branches:
            - "main"
        tags:
            - "infisical/v*.*.*-postgres"
    workflow_dispatch:

jobs:
    infisical-tests:
        name: Run tests before deployment
        # https://docs.github.com/en/actions/using-workflows/reusing-workflows#overview
        uses: ./.github/workflows/run-backend-tests.yml

    infisical-standalone:
        name: Build infisical standalone image postgres
        runs-on: ubuntu-latest
        needs: [infisical-tests]
        steps:
            - name: Extract version from tag
              id: extract_version
              run: echo "::set-output name=version::${GITHUB_REF_NAME#infisical/}"
            - name: ☁️ Checkout source
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: 📦 Install dependencies to test all dependencies
              run: npm ci --only-production
              working-directory: backend
            - name: version output
              run: |
                  echo "Output Value: ${{ steps.version.outputs.major }}"
                  echo "Output Value: ${{ steps.version.outputs.minor }}"
                  echo "Output Value: ${{ steps.version.outputs.patch }}"
                  echo "Output Value: ${{ steps.version.outputs.version }}"
                  echo "Output Value: ${{ steps.version.outputs.version_type }}"
                  echo "Output Value: ${{ steps.version.outputs.increment }}"
            - name: Save commit hashes for tag
              id: commit
              uses: pr-mpt/actions-commit-hash@v2
            - name: 🔧 Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: 🐋 Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Set up Depot CLI
              uses: depot/setup-action@v1
            - name: 📦 Build backend and export to Docker
              uses: docker/build-push-action@v3
              with:
                  push: true
                  sbom: true
                  provenance: true
                  context: .
                  tags: |
                      solomonai/developer-platform:latest-postgres
                      solomonai/developer-platform:latest
                      solomonai/developer-platform:${{ steps.commit.outputs.short }}
                      solomonai/developer-platform:${{ steps.extract_version.outputs.version }}
                  platforms: linux/amd64,linux/arm64
                  file: Dockerfile.standalone-infisical
                  build-args: |
                      POSTHOG_API_KEY=${{ secrets.PUBLIC_POSTHOG_API_KEY }}
                      INFISICAL_PLATFORM_VERSION=${{ steps.extract_version.outputs.version }}

    infisical-fips-standalone:
        name: Build infisical standalone image postgres
        runs-on: ubuntu-latest
        needs: [infisical-tests]
        steps:
            - name: Extract version from tag
              id: extract_version
              run: echo "::set-output name=version::${GITHUB_REF_NAME#infisical/}"
            - name: ☁️ Checkout source
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: 📦 Install dependencies to test all dependencies
              run: npm ci --only-production
              working-directory: backend
            - name: version output
              run: |
                  echo "Output Value: ${{ steps.version.outputs.major }}"
                  echo "Output Value: ${{ steps.version.outputs.minor }}"
                  echo "Output Value: ${{ steps.version.outputs.patch }}"
                  echo "Output Value: ${{ steps.version.outputs.version }}"
                  echo "Output Value: ${{ steps.version.outputs.version_type }}"
                  echo "Output Value: ${{ steps.version.outputs.increment }}"
            - name: Save commit hashes for tag
              id: commit
              uses: pr-mpt/actions-commit-hash@v2
            - name: 🔧 Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: 🐋 Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Set up Depot CLI
              uses: depot/setup-action@v1
            - name: 📦 Build backend and export to Docker
              uses: docker/build-push-action@v3
              with:
                  push: true
                  sbom: true
                  provenance: true
                  context: .
                  tags: |
                      solomonai/developer-platform-fips:latest-postgres
                      solomonai/developer-platform-fips:latest
                      solomonai/developer-platform-fips:${{ steps.commit.outputs.short }}
                      solomonai/developer-platform-fips:${{ steps.extract_version.outputs.version }}
                  platforms: linux/amd64,linux/arm64
                  file: Dockerfile.fips.standalone-infisical
                  build-args: |
                      POSTHOG_API_KEY=${{ secrets.PUBLIC_POSTHOG_API_KEY }}
                      INFISICAL_PLATFORM_VERSION=${{ steps.extract_version.outputs.version }}
